baseURL = "https://amoxicillinnn.github.io/"
languageCode = "en-us"
title = "thing"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
env = "production"
defaultTheme = "dark"             # 固定暗色模式
themePrimaryColor = "#ff6600"     # 高对比橙色主色
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
enableThemeSwitch = true
customCSS = ["css/custom.css"]    # 引入自定义 CSS

[params.homeInfoParams]
Title = "All is well."
Content = "Rest assured that everything is unfolding as it should, and all is perfectly in its place."

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archives/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4
